# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2333fc5d934924e12e427ea8f6d0c12ec5b3b4cbdcd027fb1bebfb64e6b90635b286206e715437f78eb1b02c7af7418cf4a14008222fa8721a766c13ebcf3f38

test:
  secret_key_base: a3f96446fcb8ce6a0fb81d6474f1de637f1d76afd54f6d84784b8d9b9790716bead587abd1cfa0f863866c1adf0fc2892cdc5671c90b1e60b37673d30aef613a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
